name: Build & Publish DocFX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Mono
      run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          sudo apt-add-repository 'deb https://download.mono-project.com/repo/ubuntu stable-focal main'
          sudo apt install mono-complete
    
    - name: Fix the links
      run: bash create_docfx_link.sh
    
    - name: Download DocFX
      run: |
          curl "https://github.com/dotnet/docfx/releases/download/v2.58.9/docfx.zip" -L > docfx.zip
          unzip docfx.zip -d docfx
    
    - name: Build docs
      run: |
          bash create_docfx_link.sh
          mono docfx/docfx.exe docfx_project/docfx.json
    
    - name: Publish GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx_project/_site
        enable_jekyll: true
